name: Live Action Events
favicon: null
layout_spectrum: 0
typography_spectrum: 0.34489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b2b2b2'
    - '#98cb00'
    - '#8b329a'
    - '#98874d'
  brandStrength: 0
  lightness: 0.02851238544099033
  saturation: 0.9868569618556648
  rhythmicContrast: 0.75
purpose: []
